### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by phyukhaing7** [mikkkeldp/hard-attention-image-captioning#1]
For the training, Feature are needed. How to extract features previously?
I faced with the following error.

`FileNotFoundError: [Errno 2] No such file or directory: 'feature_dict.pickle'`

**Comment by mikkkeldp** [comment]
I removed the lines, should be working now. Let me know if you can train

**Comment by phyukhaing7** [comment]
Yes, it is working.
Thanks a lot for your reply.
